name: Deploy BentoPDF to Vercel

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflow/deploy-vercel.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Extract specific source code release
        run: |
          curl -L https://github.com/alam00000/bentopdf/archive/refs/tags/v2.8.8.tar.gz -o bentopdf.tar.gz
          tar -xzf bentopdf.tar.gz --strip-components=1
          rm bentopdf.tar.gz

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        env:
          SIMPLE_MODE: "true"
          HUSKY: "0"
          BASE_URL: "/"
        run: vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
